### ISSUE TITLE
No module 'xlrd' and FileNotFoundError

### ISSUE THREAD

**Issue by SenthilCaesar** [pnlbwh/structuralQC#5]
**_./cli-modules/structuralQC.py -i ref_data/1001-t1w-xc.nrrd -t t1 --fixedImg mni_icbm152_nlin_sym_09a/mniTemplateT1.nii.gz -o /tmp/_**

Total elapsed time: 683.5
Registration successful of 1001-t1w-xc.nrrd
Checking quality ...
Traceback (most recent call last):
  File "/rfanfs/pnl-zorro/home/sq566/Downloads/conda/envs/structQC/lib/python3.7/site-packages/pandas/io/excel.py", line 391, in __init__
    import xlrd
ModuleNotFoundError: No module named 'xlrd'

-----------------------------------------------------------------------------------------------------------------------------------
pip install xlrd
-----------------------------------------------------------------------------------------------------------------------------------

**_./cli-modules/structuralQC.py -i ref_data/1001-t1w-xc.nrrd -t t1 --fixedImg mni_icbm152_nlin_sym_09a/mniTemplateT1.nii.gz -o /tmp_**

Registration successful of 1001-t1w-xc.nrrd
Checking quality ...
Traceback (most recent call last):
  File "./cli-modules/structuralQC.py", line 89, in <module>
    QC.run()
  File "/rfanfs/pnl-zorro/home/sq566/Downloads/conda/envs/structQC/lib/python3.7/site-packages/plumbum/cli/application.py", line 572, in run
    retcode = inst.main(*tailargs)
  File "./cli-modules/structuralQC.py", line 84, in main
    processImage(self.img, self.outDir, self.modality)
  File "/rfanfs/pnl-zorro/home/sq566/Downloads/StructuralQC/structuralQC/cli-modules/calculation.py", line 88, in processImage
    prediction= predictQuality(dim, H_test, modality, fid)
  File "/rfanfs/pnl-zorro/home/sq566/Downloads/StructuralQC/structuralQC/cli-modules/calculation.py", line 95, in predictQuality
    subjects, ratings= loadExcel(excelFile, modality)
  File "/rfanfs/pnl-zorro/home/sq566/Downloads/StructuralQC/structuralQC/cli-modules/loadFile.py", line 34, in loadExcel
    df = pd.read_excel(fileName)
  File "/rfanfs/pnl-zorro/home/sq566/Downloads/conda/envs/structQC/lib/python3.7/site-packages/pandas/util/_decorators.py", line 188, in wrapper
    return func(*args, **kwargs)
  File "/rfanfs/pnl-zorro/home/sq566/Downloads/conda/envs/structQC/lib/python3.7/site-packages/pandas/util/_decorators.py", line 188, in wrapper
    return func(*args, **kwargs)
  File "/rfanfs/pnl-zorro/home/sq566/Downloads/conda/envs/structQC/lib/python3.7/site-packages/pandas/io/excel.py", line 350, in read_excel
    io = ExcelFile(io, engine=engine)
  File "/rfanfs/pnl-zorro/home/sq566/Downloads/conda/envs/structQC/lib/python3.7/site-packages/pandas/io/excel.py", line 653, in __init__
    self._reader = self._engines[engine](self._io)
  File "/rfanfs/pnl-zorro/home/sq566/Downloads/conda/envs/structQC/lib/python3.7/site-packages/pandas/io/excel.py", line 424, in __init__
    self.book = xlrd.open_workbook(filepath_or_buffer)
  File "/rfanfs/pnl-zorro/home/sq566/Downloads/conda/envs/structQC/lib/python3.7/site-packages/xlrd/__init__.py", line 111, in open_workbook
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by tashrifbillah** [comment]
Thank for finding it out. We also need a visual_qc file. I have copied that in `/tmp/visual_qc.xlsx`. I am also updating the reference data.

`xlrd` dependency is added.

**Comment by SenthilCaesar** [comment]
After placing the visual_qc.xlsx in place, command ran successfully

Total elapsed time: 1911
Registration successful of 1001-t2w-xc.nrrd
Checking quality ...
4 pass
Time taken in structural QC 1987.0419359207153 seconds

**Comment by tashrifbillah** [comment]
Fixed by https://github.com/pnlbwh/structuralQC/commit/ee79b1c373a17dd89902d1cb0c8255aabf283524
